sonar.projectKey=jfk-itinerary-backend
sonar.projectName=jfk-itinerary-backend
sonar.exclusions=src/mock/**, node_modules/**
-Dsonar.sources=src \
-Dsonar.scm.disabled=true
-Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
