sonar.projectKey=jfk-itinerary-backend
sonar.projectName=jfk-itinerary-backend
sonar.sources=src
sonar.tests=src/tests
# Excluir archivos que inflan las duplicaciones
sonar.exclusions=\
  src/mock/**,\
  **/*.config.js,\
  src/tests/**,\
  **/node_modules/**

# Excluir del análisis de duplicaciones
sonar.cpd.exclusions=\
  src/mock/**

# Ruta al reporte de cobertura de Jest
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.javascript.environments=node
